
api-key: zdUP8ElJv1cehFM0rsZVSQN7uBVxlDnu4diHlLSb
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
# debug: true
# trace: true
api-nasa-endpoint: https://api.nasa.gov/neo/rest/v1/feed
dev-url: 'http://localhost:'